### ISSUE TITLE
Cap Issue

### ISSUE THREAD

**Issue by mishahawthorn** [tatebosler/ifantasyfitness#15]
The cap is 40 points per week. In the last 7 days, you have logged points.

If the # you capped is 0, it doesn't show it.

**Comment by tatebosler** [comment]
That's because right now there is no active season in competition mode, so `$team_data` is an empty array, especially `$team_data['week_strength']` or `week_sports`. Fixing!

**Comment by tatebosler** [comment]
Fix is live, nice and easy. Thanks for reporting! :)
