### ISSUE TITLE
Point Counter in Navbar

### ISSUE THREAD

**Issue by mishahawthorn** [tatebosler/ifantasyfitness#17]
Have a live counter of your own points in the navbar, and maybe even a "total points logged" ticker for extra swag.

**Comment by tatebosler** [comment]
Something like this?
![screen shot 2014-05-21 at 10 06 14 pm](https://cloud.githubusercontent.com/assets/5247846/3049401/1ee8d26a-e15e-11e3-9e71-b0898474c37a.png)

**Comment by mishahawthorn** [comment]
Yis!

**Comment by tatebosler** [comment]
OK, it's up. There's just an issue with the colors that I'll need to either fix myself or get Bootstrap to fix, it's issue twbs/bootstrap#13654, but it's minor and aesthetic. Functionally, it's up.

**Comment by tatebosler** [comment]
Colors fixed in 26438358ceac99924ed1fc012ddeb243236340b0.
