### ISSUE TITLE
sign up for fantasy fitness?

### ISSUE THREAD

**Issue by donovans4** [tatebosler/ifantasyfitness#4]
there was no confirmation that it worked when I signed up for Fantasy Fitness. how do we know that we are in fact registered?

**Comment by tatebosler** [comment]
Hi, If you tried in the last hour then it should have given you an OK. I don't see your account listed so try it again, something must not have gone through with Google or Facebook.

School wi-fi is horrible so I would recommend not signing up there.

If your account exists but you aren't registered for the season, you go to `/register?season=2014` by clicking the big red button on your dashboard.

Hope this helps!

**Comment by tatebosler** [comment]
It looks like your registration has gone through OK. If you have any further problems just make a new comment on the issue or send me an email.
